sequenceDiagram
        participant Buyer
        participant OEF Node
        participant Seller
        Seller->>OEF Node: (1) register service;
        Seller->>Seller: run(), waiting for messages...
        activate Seller
        Buyer->>OEF Node: (2) search services;
        Buyer->>Buyer: run(), waiting for messages...
        activate Buyer
        OEF Node->>Buyer: (3) search result;
        activate Buyer
        note left of Buyer: on_search_result() called
        Buyer->>OEF Node: (4) CFP(query):
        deactivate Buyer
        OEF Node->>Seller: CFP(query);
        activate Seller
        note right of Seller:on_cfp() called;
        Seller ->>OEF Node: (5) Propose(id, price)
        deactivate Seller
        OEF Node ->>Buyer: Propose(id, price)
        activate Buyer
        note left of Buyer: on_propose() called;
        Buyer->>OEF Node: (6) Accept(id)
        deactivate Buyer
        OEF Node->>Seller: Accept(id)
        activate Seller
        note right of Seller:on_accept() called;
        Seller ->>OEF Node: (7) Message(temperature)
        Seller ->>OEF Node: Message(air_pressure)
        Seller ->>OEF Node: Message(humidity)
        deactivate Seller
        OEF Node ->>Buyer: Message(temperature)
        OEF Node ->>Buyer: Message(air_pressure)
        OEF Node ->>Buyer: Message(humidity)
        activate Buyer
        note left of Buyer: on_message() called;
        Buyer->>Buyer: stop()
        deactivate Buyer
        deactivate Seller
        deactivate Buyer